<?php

use Illuminate\Database\Seeder;
use Faker\Factory;
use App\Photo;

class PhotosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Factory::create();
        Photo::truncate();
        // foreach(range(1, 10) as $i) {
        // 	$photo = Photo::create([
        //         //'user_id' => $i,
        //         'user_id' => 1,
        // 		'name' => $faker->sentence,
        // 		'description' => $faker->paragraph(mt_rand(10, 20)),
        // 		'image' => 'test.jpg'
        // 	]);
        	
        // }

        DB::table('photos')->insert([
            'user_id' => 1,
            'name' => 'Scientists',
            'description' => 'Solvay Conference 1932',
            'image' => '1.jpeg'
        ]);

        DB::table('photos')->insert([
            'user_id' => 1,
            'name' => 'Albert Einstein',
            'description' => 'German American Physicist',
            'image' => '2.jpeg'
        ]);

        DB::table('photos')->insert([
            'user_id' => 1,
            'name' => 'Earth',
            'description' => 'This high-res time-lapse sequences captured by astronauts aboard the International Space Station give us a beautiful and clear view of our planet',
            'image' => '3.jpeg'
        ]);

        DB::table('photos')->insert([
            'user_id' => 1,
            'name' => 'Plasma',
            'description' => 'Plasma is one of the four fundamental states of matter, and was first described by chemist Irving Langmuir in the 1920\'s. Unlike the other three states, solid, liquid, and gas, plasma does not exist freely on the Earth\'s surface under normal conditions. Plasma can be artificially generated by heating or subjecting a neutral gas to a strong electromagnetic field to the point an ionised gaseous substance becomes increasingly electrically conductive, and long-range electromagnetic fields dominate the behaviour of the matter.',
            'image' => '4.jpeg'
        ]);

        DB::table('photos')->insert([
            'user_id' => 1,
            'name' => 'Microscope',
            'description' => 'Looking into the very tiny',
            'image' => '5.jpeg'
        ]);

        DB::table('photos')->insert([
            'user_id' => 1,
            'name' => 'Newton\'s Cradle',
            'description' => 'This device demonstrates conservation of momentum and energy using a series of swinging spheres. When one sphere at the end is lifted and released, it strikes the stationary spheres, transmitting a force through the stationary spheres that pushes the last sphere upward. The last sphere swings back and strikes the still nearly stationary spheres, repeating the effect in the opposite direction.',
            'image' => '6.jpeg'
        ]);
    }
}
